import { Comic } from './dto/comic.dto';

export const COMICS: Comic[] = [
  {
    index: 0,
    title: 'Sailing Rigs',
    alt: 'A comparison of different sailing rig configurations.',
    imgUrl: 'https://imgs.xkcd.com/comics/sailing_rigs.png',
  },
  {
    index: 1,
    title: 'Planetary Alignment',
    alt: 'Planetary alignments happen all the time and have negligible gravitational effects.',
    imgUrl: 'https://imgs.xkcd.com/comics/planetary_alignment.png',
  },
  {
    index: 2,
    title: 'Superstition',
    alt: 'I calculated the odds and they are exactly what you would expect from random chance.',
    imgUrl: 'https://imgs.xkcd.com/comics/superstition.png',
  },
  {
    index: 3,
    title: 'Tensegrity',
    alt: 'Floating tables held up by tension cables look cool but are not very practical.',
    imgUrl: 'https://imgs.xkcd.com/comics/tensegrity.png',
  },
  {
    index: 4,
    title: 'Conic Sections',
    alt: 'Slice a cone at different angles to get circles, ellipses, parabolas, and hyperbolas.',
    imgUrl: 'https://imgs.xkcd.com/comics/conic_sections.png',
  },
  {
    index: 5,
    title: 'Anyone Else Here',
    alt: 'That awkward moment when you arrive early to a meeting.',
    imgUrl: 'https://imgs.xkcd.com/comics/anyone_else_here.png',
  },
  {
    index: 6,
    title: 'High Altitude Cooking Instructions',
    alt: 'At high altitudes, water boils at lower temperatures, so cook things longer.',
    imgUrl: 'https://imgs.xkcd.com/comics/high_altitude_cooking_instructions.png',
  },
  {
    index: 7,
    title: 'Truly Universal Outlet',
    alt: 'A power outlet that accepts every plug type from every country, plus USB.',
    imgUrl: 'https://imgs.xkcd.com/comics/truly_universal_outlet.png',
  },
  {
    index: 8,
    title: 'Sauropods',
    alt: 'Long-necked dinosaurs were basically biological cranes that ate leaves.',
    imgUrl: 'https://imgs.xkcd.com/comics/sauropods.png',
  },
  {
    index: 9,
    title: 'Funny Numbers',
    alt: 'Numbers that make you chuckle: 69, 420, and 8008 on a calculator.',
    imgUrl: 'https://imgs.xkcd.com/comics/funny_numbers.png',
  },
  {
    index: 10,
    title: 'Pole Vault Pole',
    alt: 'The pole used in pole vaulting is made of fiberglass and bends dramatically.',
    imgUrl: 'https://imgs.xkcd.com/comics/pole_vault_pole.png',
  },
  {
    index: 11,
    title: 'Telescope Types',
    alt: 'Refractors, reflectors, and radio telescopes all share one problem: city lights.',
    imgUrl: 'https://imgs.xkcd.com/comics/telescope_types.png',
  },
  {
    index: 12,
    title: 'Jumping Frog Radius',
    alt: 'Frogs already knew calculus millions of years before Newton.',
    imgUrl: 'https://imgs.xkcd.com/comics/jumping_frog_radius.png',
  },
  {
    index: 13,
    title: 'Apples',
    alt: 'Grocery stores only sell six apple varieties out of thousands that exist.',
    imgUrl: 'https://imgs.xkcd.com/comics/apples.png',
  },
  {
    index: 14,
    title: 'Fishing',
    alt: 'Fishing is just an excuse to sit by water and do nothing.',
    imgUrl: 'https://imgs.xkcd.com/comics/fishing.png',
  },
  {
    index: 15,
    title: 'Hyperacute Interdynamics',
    alt: 'Using unnecessarily complex terminology to sound impressive at conferences.',
    imgUrl: 'https://imgs.xkcd.com/comics/hyperacute_interdynamics.png',
  },
  {
    index: 16,
    title: 'Earthquake Prediction Flowchart',
    alt: 'If an earthquake happened, you predicted it. If not, predict one for tomorrow.',
    imgUrl: 'https://imgs.xkcd.com/comics/earthquake_prediction_flowchart.png',
  },
  {
    index: 17,
    title: 'Metric Tip',
    alt: 'To convert Celsius to Fahrenheit, remember -40° is the same in both.',
    imgUrl: 'https://imgs.xkcd.com/comics/metric_tip.png',
  },
  {
    index: 18,
    title: 'Repair Vindexeo',
    alt: 'Every repair tutorial skips over the 47 hindexden clips and two broken tabs.',
    imgUrl: 'https://imgs.xkcd.com/comics/repair_vindexeo.png',
  },
  {
    index: 19,
    title: 'Chessboard Alignment',
    alt: 'The bottom-right square should be white. If it is black, you set up wrong.',
    imgUrl: 'https://imgs.xkcd.com/comics/chessboard_alignment.png',
  },
  {
    index: 20,
    title: 'Inverted Catenaries',
    alt: 'A catenary is the curve a hanging chain makes. Flip it for a perfect arch.',
    imgUrl: 'https://imgs.xkcd.com/comics/inverted_catenaries.png',
  },
  {
    index: 21,
    title: 'Website Task Flowchart',
    alt: 'Try task, make account, forget password, give up and use competitor site.',
    imgUrl: 'https://imgs.xkcd.com/comics/website_task_flowchart.png',
  },
  {
    index: 22,
    title: 'Brindexge Clearance',
    alt: 'The sign says 11. Your truck is 12. Math says no, confindexence says maybe.',
    imgUrl: 'https://imgs.xkcd.com/comics/brindexge_clearance.png',
  },
  {
    index: 23,
    title: 'Satellite Imagery',
    alt: 'Google Earth images are always from 2009 and still show the old roof.',
    imgUrl: 'https://imgs.xkcd.com/comics/satellite_imagery.png',
  },
  {
    index: 24,
    title: 'Airspeed',
    alt: 'Pilots care about indicated airspeed, true airspeed, and ground speed.',
    imgUrl: 'https://imgs.xkcd.com/comics/airspeed.png',
  },
  {
    index: 25,
    title: 'Document Forgery',
    alt: 'Comic Sans did not exist in 1985, so your vintage letter is clearly fake.',
    imgUrl: 'https://imgs.xkcd.com/comics/document_forgery.png',
  },
];
